# Generated by Django 4.2.11 on 2024-04-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_booking_id_alter_menu_id_alter_menu_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="No_of_guests",
            field=models.IntegerField(),
        ),
    ]
