# Generated by Django 4.2.11 on 2024-04-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_rename_booking_bookings_rename_menu_menus"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bookings",
            new_name="Booking",
        ),
        migrations.RenameModel(
            old_name="Menus",
            new_name="Menu",
        ),
    ]
